---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: detect-private-key
