AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Polizas CRUD API.

Globals:
  Function:
    Timeout: 3

Resources:
  NestJSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs18.x
      Events:
        NestJSApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  NestJSApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"