AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Polizas y Amparos CRUD API.

Globals:
  Function:
    Timeout: 3

Resources:
  PolizasCrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: lambda.handler
      Runtime: nodejs18.x
      Events:
        PolizasApi:
          Type: Api
          Properties:
            Path: /polizas/{proxy+}
            Method: ANY
        AmparosApi:
          Type: Api
          Properties:
            Path: /amparos/{proxy+}
            Method: ANY

Outputs:
  PolizasAmparosCrudApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PolizasApiEndpoint:
    Description: "Polizas API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/polizas/"
  AmparosApiEndpoint:
    Description: "Amparos API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/amparos/"