openapi: 3.0.0
paths:
  /polizas:
    get:
      operationId: PolizasController_findAll
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: PolizasController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearPolizaDto'
      responses:
        '201':
          description: ''
  /polizas/{id}:
    get:
      operationId: PolizasController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    put:
      operationId: PolizasController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePolizaDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: PolizasController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /polizas/{id}/amparos:
    get:
      operationId: PolizasController_findAmparos
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
  /amparos:
    get:
      operationId: AmparoPolizasController_findAll
      parameters: []
      responses:
        '200':
          description: ''
    post:
      operationId: AmparoPolizasController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearAmparoPolizaDto'
      responses:
        '201':
          description: ''
  /amparos/{id}:
    get:
      operationId: AmparoPolizasController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
    put:
      operationId: AmparoPolizasController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAmparoPolizaDto'
      responses:
        '200':
          description: ''
    delete:
      operationId: AmparoPolizasController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
info:
  title: Polizas API CRUD
  description: API
  version: '1.0'
  contact: {}
tags:
  - name: API
    description: ''
servers: []
components:
  schemas:
    CrearPolizaDto:
      type: object
      properties: {}
    UpdatePolizaDto:
      type: object
      properties: {}
    CrearAmparoPolizaDto:
      type: object
      properties: {}
    UpdateAmparoPolizaDto:
      type: object
      properties: {}
