openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /polizas:
    get:
      operationId: PolizasController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_0
        - Polizas
    post:
      operationId: PolizasController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrearPolizaDto'
      responses:
        '201':
          description: ''
      tags: *ref_0
  /polizas/{id}:
    get:
      operationId: PolizasController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
    put:
      operationId: PolizasController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePolizaDto'
      responses:
        '200':
          description: ''
      tags: *ref_0
    delete:
      operationId: PolizasController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
  /polizas/{id}/amparos:
    get:
      operationId: PolizasController_findAmparos
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_0
  /amparos:
    get:
      operationId: AmparoPolizasController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      summary: Listar todos los amparos
      tags: &ref_1
        - amparos
    post:
      operationId: AmparoPolizasController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '201':
          description: ''
      summary: Crear múltiples amparos de pólizas
      tags: *ref_1
  /amparos/{id}:
    get:
      operationId: AmparoPolizasController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
    put:
      operationId: AmparoPolizasController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAmparoPolizaDto'
      responses:
        '200':
          description: ''
      tags: *ref_1
    delete:
      operationId: AmparoPolizasController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
  /amparos/contrato/{id}:
    get:
      operationId: AmparoPolizasController_findByContractId
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      summary: Listar todos los amparos de un contrato
      tags: *ref_1
info:
  title: Pólizas API CRUD
  description: API para Pólizas
  version: '1.0'
  contact: {}
tags:
  - name: polizas
    description: ''
servers: []
components:
  schemas:
    CrearPolizaDto:
      type: object
      properties: {}
    UpdatePolizaDto:
      type: object
      properties: {}
    UpdateAmparoPolizaDto:
      type: object
      properties: {}
